# docker-compose.yaml
version: '3.7'

services:
    app:
        build:   { context: . }
        ports:   [ '8000:8000' ]
        volumes: [ '.:/www' ]
        networks:
            - db-network
        depends_on:
            - database

    database:
        image: mariadb
        volumes:
            - database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: sf4vts
        networks:
            - db-network

networks:
    db-network:

volumes:
    database: ~
